/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    'artist-profile': ArtistProfile;
    releases: Release;
    'tour-shows': TourShow;
    'blog-posts': BlogPost;
    'podcast-episodes': PodcastEpisode;
    'podcast-stats': PodcastStat;
    'merch-products': MerchProduct;
    'media-gallery': MediaGallery;
    subscriptions: Subscription;
    'contact-submissions': ContactSubmission;
    orders: Order;
    carts: Cart;
    'email-templates': EmailTemplate;
    'email-logs': EmailLog;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'artist-profile': ArtistProfileSelect<false> | ArtistProfileSelect<true>;
    releases: ReleasesSelect<false> | ReleasesSelect<true>;
    'tour-shows': TourShowsSelect<false> | TourShowsSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    'podcast-episodes': PodcastEpisodesSelect<false> | PodcastEpisodesSelect<true>;
    'podcast-stats': PodcastStatsSelect<false> | PodcastStatsSelect<true>;
    'merch-products': MerchProductsSelect<false> | MerchProductsSelect<true>;
    'media-gallery': MediaGallerySelect<false> | MediaGallerySelect<true>;
    subscriptions: SubscriptionsSelect<false> | SubscriptionsSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    carts: CartsSelect<false> | CartsSelect<true>;
    'email-templates': EmailTemplatesSelect<false> | EmailTemplatesSelect<true>;
    'email-logs': EmailLogsSelect<false> | EmailLogsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    navigation: Navigation;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "artist-profile".
 */
export interface ArtistProfile {
  id: number;
  name: string;
  tagline?: string | null;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  heroImage?: (number | null) | Media;
  portraitImage?: (number | null) | Media;
  /**
   * Full-bleed background photo behind the bio section on /about. A dark overlay is applied automatically for text readability. Leave empty to fall back to the existing two-column layout.
   */
  aboutBackgroundImage?: (number | null) | Media;
  principles?:
    | {
        icon?: string | null;
        title?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  timeline?:
    | {
        year?: number | null;
        title?: string | null;
        description?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  pressQuotes?:
    | {
        quote?: string | null;
        author?: string | null;
        publication?: string | null;
        id?: string | null;
      }[]
    | null;
  socialLinks?: {
    instagram?: string | null;
    tiktok?: string | null;
    youtube?: string | null;
    soundcloud?: string | null;
    /**
     * Public Linktree URL — shown as a pill next to the logo on every page.
     */
    linktree?: string | null;
    /**
     * Artist-wide stream landing page — used by the "Find the music everywhere" button on the music page. Typically a Linktree, Songwhip, or distributor aggregator.
     */
    streamUrl?: string | null;
  };
  contactEmails?: {
    general?: string | null;
    booking?: string | null;
    press?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: string | null;
  category?: ('Release Cover' | 'Press Photo' | 'Merch' | 'Blog' | 'Artist' | 'Other') | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "releases".
 */
export interface Release {
  id: number;
  title: string;
  slug: string;
  type?: ('EP' | 'Album' | 'Single') | null;
  coverImage?: (number | null) | Media;
  releaseDate?: string | null;
  description?: string | null;
  featured?: boolean | null;
  tracks?:
    | {
        number?: number | null;
        title?: string | null;
        subtitle?: string | null;
        duration?: string | null;
        badge?: string | null;
        previewUrl?: string | null;
        audioFile?: (number | null) | Media;
        /**
         * Per-track USD price. Leave blank if not individually sold.
         */
        priceUSD?: number | null;
        /**
         * Per-track NGN price.
         */
        priceNGN?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Where the Stream button on the storefront should send listeners — typically a Linktree, Songwhip, or distributor landing page that fans out to every platform.
   */
  streamUrl?: string | null;
  distributionTiers?:
    | {
        label?: string | null;
        description?: string | null;
        priceUSD: number;
        priceNGN: number;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tour-shows".
 */
export interface TourShow {
  id: number;
  venue: string;
  city: string;
  country?: string | null;
  date: string;
  time?: string | null;
  type?: ('Headline' | 'Festival' | 'Support' | 'Private') | null;
  soldOut?: boolean | null;
  ticketUrl?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  title: string;
  slug: string;
  coverImage?: (number | null) | Media;
  category?: ('Tour' | 'Studio' | 'Personal' | 'News' | 'Behind The Scenes' | 'Other') | null;
  excerpt?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  publishedDate: string;
  featured?: boolean | null;
  /**
   * Auto-calculated from content length (~200 words per minute)
   */
  readTime?: number | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "podcast-episodes".
 */
export interface PodcastEpisode {
  id: number;
  episodeNumber: number;
  title: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  publishDate?: string | null;
  duration?: string | null;
  audioUrl?: string | null;
  guestName?: string | null;
  guestBio?: string | null;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "podcast-stats".
 */
export interface PodcastStat {
  id: number;
  totalEpisodes?: number | null;
  totalListeners?: number | null;
  averageRating?: number | null;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "merch-products".
 */
export interface MerchProduct {
  id: number;
  name: string;
  slug: string;
  images?:
    | {
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  category?: ('Apparel' | 'Music' | 'Digital' | 'Bundle' | 'Accessory') | null;
  /**
   * Default USD price. Charged to PayPal customers and shown to non-NG visitors.
   */
  priceUSD: number;
  /**
   * Default NGN price. Charged to Credo customers and shown to NG visitors.
   */
  priceNGN: number;
  /**
   * Original USD price for strike-through display. Leave blank if not on sale.
   */
  compareAtPriceUSD?: number | null;
  /**
   * Original NGN price for strike-through display.
   */
  compareAtPriceNGN?: number | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Define the axes of variation (e.g. Size, Color). Each variant below must specify a value for every option type.
   */
  optionTypes?:
    | {
        name: string;
        values?:
          | {
              value: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Each row is a sellable SKU. Provide a value for every option type defined above.
   */
  variants?:
    | {
        optionValues?:
          | {
              type: string;
              value: string;
              id?: string | null;
            }[]
          | null;
        sku: string;
        priceUSD: number;
        priceNGN: number;
        stock: number;
        image?: (number | null) | Media;
        available?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Manual override. When unchecked, the product is hidden from the storefront regardless of variant stock.
   */
  inStock?: boolean | null;
  badge?: string | null;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-gallery".
 */
export interface MediaGallery {
  id: number;
  type?: ('Photo' | 'Video' | 'Press Quote' | 'EPK Download') | null;
  title?: string | null;
  file?: (number | null) | Media;
  thumbnail?: (number | null) | Media;
  videoUrl?: string | null;
  quote?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  publication?: string | null;
  author?: string | null;
  fileSize?: string | null;
  fileType?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscriptions".
 */
export interface Subscription {
  id: number;
  email: string;
  firstName?: string | null;
  lastName?: string | null;
  type?: ('Fan Club' | 'Newsletter' | 'Tour Notifications') | null;
  subscribedAt?: string | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  name: string;
  email: string;
  organization?: string | null;
  inquiryType?: ('Booking' | 'Press' | 'Collaboration' | 'Other') | null;
  eventDate?: string | null;
  budget?: string | null;
  message: string;
  submittedAt?: string | null;
  status?: ('New' | 'Read' | 'Replied' | 'Archived') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  orderNumber?: string | null;
  customerEmail: string;
  customerName?: string | null;
  /**
   * Required for physical goods. Leave empty for digital-only orders.
   */
  shippingAddress?: {
    line1?: string | null;
    line2?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
    country?: string | null;
    phone?: string | null;
  };
  items?:
    | {
        type?: ('Track' | 'EP' | 'Merch') | null;
        /**
         * Source merch-products or releases doc ID at the time of purchase.
         */
        productId?: string | null;
        /**
         * For merch with variants, the chosen variant array row ID.
         */
        variantId?: string | null;
        name?: string | null;
        /**
         * Human-readable variant description, e.g. "Size: M / Color: Black".
         */
        variantLabel?: string | null;
        sku?: string | null;
        priceUSD: number;
        priceNGN: number;
        quantity?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Sum of line items in displayCurrency, before shipping/tax.
   */
  subtotal: number;
  shipping?: number | null;
  total: number;
  /**
   * Currency the customer saw at checkout. subtotal/shipping/total are in this currency.
   */
  displayCurrency: 'USD' | 'NGN';
  status?: ('Pending Payment' | 'Paid' | 'Fulfilled' | 'Shipped' | 'Refunded' | 'Cancelled' | 'Expired') | null;
  paymentProvider?: ('credo' | 'paypal') | null;
  /**
   * Currency the payment was actually captured in.
   */
  paidCurrency?: ('USD' | 'NGN') | null;
  /**
   * Amount actually captured in paidCurrency.
   */
  paidAmount?: number | null;
  /**
   * Credo transRef used for verification.
   */
  credoReference?: string | null;
  /**
   * URL to redirect the customer to complete a Credo payment.
   */
  credoAuthorizationUrl?: string | null;
  /**
   * PayPal Orders v2 order ID returned by createOrder.
   */
  paypalOrderId?: string | null;
  /**
   * PayPal capture ID returned by captureOrder.
   */
  paypalCaptureId?: string | null;
  /**
   * Unguessable token for self-service order status lookup.
   */
  lookupToken?: string | null;
  /**
   * Per-browser identifier copied from the cart cookie. Used to build per-browser order history without auth.
   */
  customerToken?: string | null;
  downloadToken?: string | null;
  downloadExpiresAt?: string | null;
  downloadCount?: number | null;
  /**
   * Idempotency record of transactional emails fired for this order.
   */
  emailsSent?:
    | {
        templateKey?: string | null;
        sentAt?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Internal notes. Not shown to the customer.
   */
  notes?: string | null;
  createdAt: string;
  updatedAt: string;
}
/**
 * Anonymous shopping carts. Read/write happens through public cart endpoints authorized by the cart_id cookie — never directly via admin UI.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts".
 */
export interface Cart {
  id: number;
  cartId: string;
  customerEmail?: string | null;
  /**
   * Long-lived per-browser identifier. Copied into Orders.customerToken at checkout.
   */
  customerToken?: string | null;
  displayCurrency: 'USD' | 'NGN';
  items?:
    | {
        type?: ('Track' | 'EP' | 'Merch') | null;
        productId: string;
        variantId?: string | null;
        name?: string | null;
        variantLabel?: string | null;
        sku?: string | null;
        priceUSD: number;
        priceNGN: number;
        quantity?: number | null;
        imageUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  itemCount?: number | null;
  lastActivityAt?: string | null;
  abandonedEmailSentAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Subject and body content for every transactional email sent by the site. Use {{variableName}} placeholders — the substitution map for each key is documented below.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-templates".
 */
export interface EmailTemplate {
  id: number;
  /**
   * Identifies which system event triggers this template.
   */
  key:
    | 'order.paid'
    | 'order.fulfilled'
    | 'order.shipped'
    | 'order.refunded'
    | 'order.cancelled'
    | 'order.magic-link'
    | 'cart.abandoned'
    | 'welcome.newsletter'
    | 'contact.auto-reply';
  /**
   * Uncheck to disable sends for this template without deleting it.
   */
  enabled?: boolean | null;
  /**
   * Email subject line. Supports {{variables}}.
   */
  subject: string;
  /**
   * Email body. Supports {{variables}} anywhere in the rich text.
   */
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Defaults to the site sender if blank.
   */
  fromName?: string | null;
  /**
   * Must be a verified Resend sender domain.
   */
  fromEmail?: string | null;
  replyTo?: string | null;
  /**
   * Reference list of variables available for the selected key. Auto-updated when you save the template.
   */
  variableDocs?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Record of every transactional email send. Read-only — populated by sendTemplated().
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-logs".
 */
export interface EmailLog {
  id: number;
  templateKey: string;
  to: string;
  subject?: string | null;
  status: 'queued' | 'sent' | 'failed';
  resendId?: string | null;
  order?: (number | null) | Order;
  error?: string | null;
  sentAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'admin' | 'editor' | 'viewer';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'artist-profile';
        value: number | ArtistProfile;
      } | null)
    | ({
        relationTo: 'releases';
        value: number | Release;
      } | null)
    | ({
        relationTo: 'tour-shows';
        value: number | TourShow;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'podcast-episodes';
        value: number | PodcastEpisode;
      } | null)
    | ({
        relationTo: 'podcast-stats';
        value: number | PodcastStat;
      } | null)
    | ({
        relationTo: 'merch-products';
        value: number | MerchProduct;
      } | null)
    | ({
        relationTo: 'media-gallery';
        value: number | MediaGallery;
      } | null)
    | ({
        relationTo: 'subscriptions';
        value: number | Subscription;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'carts';
        value: number | Cart;
      } | null)
    | ({
        relationTo: 'email-templates';
        value: number | EmailTemplate;
      } | null)
    | ({
        relationTo: 'email-logs';
        value: number | EmailLog;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "artist-profile_select".
 */
export interface ArtistProfileSelect<T extends boolean = true> {
  name?: T;
  tagline?: T;
  bio?: T;
  heroImage?: T;
  portraitImage?: T;
  aboutBackgroundImage?: T;
  principles?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  timeline?:
    | T
    | {
        year?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  pressQuotes?:
    | T
    | {
        quote?: T;
        author?: T;
        publication?: T;
        id?: T;
      };
  socialLinks?:
    | T
    | {
        instagram?: T;
        tiktok?: T;
        youtube?: T;
        soundcloud?: T;
        linktree?: T;
        streamUrl?: T;
      };
  contactEmails?:
    | T
    | {
        general?: T;
        booking?: T;
        press?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "releases_select".
 */
export interface ReleasesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  type?: T;
  coverImage?: T;
  releaseDate?: T;
  description?: T;
  featured?: T;
  tracks?:
    | T
    | {
        number?: T;
        title?: T;
        subtitle?: T;
        duration?: T;
        badge?: T;
        previewUrl?: T;
        audioFile?: T;
        priceUSD?: T;
        priceNGN?: T;
        id?: T;
      };
  streamUrl?: T;
  distributionTiers?:
    | T
    | {
        label?: T;
        description?: T;
        priceUSD?: T;
        priceNGN?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tour-shows_select".
 */
export interface TourShowsSelect<T extends boolean = true> {
  venue?: T;
  city?: T;
  country?: T;
  date?: T;
  time?: T;
  type?: T;
  soldOut?: T;
  ticketUrl?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  coverImage?: T;
  category?: T;
  excerpt?: T;
  content?: T;
  publishedDate?: T;
  featured?: T;
  readTime?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "podcast-episodes_select".
 */
export interface PodcastEpisodesSelect<T extends boolean = true> {
  episodeNumber?: T;
  title?: T;
  description?: T;
  publishDate?: T;
  duration?: T;
  audioUrl?: T;
  guestName?: T;
  guestBio?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "podcast-stats_select".
 */
export interface PodcastStatsSelect<T extends boolean = true> {
  totalEpisodes?: T;
  totalListeners?: T;
  averageRating?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "merch-products_select".
 */
export interface MerchProductsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  category?: T;
  priceUSD?: T;
  priceNGN?: T;
  compareAtPriceUSD?: T;
  compareAtPriceNGN?: T;
  description?: T;
  optionTypes?:
    | T
    | {
        name?: T;
        values?:
          | T
          | {
              value?: T;
              id?: T;
            };
        id?: T;
      };
  variants?:
    | T
    | {
        optionValues?:
          | T
          | {
              type?: T;
              value?: T;
              id?: T;
            };
        sku?: T;
        priceUSD?: T;
        priceNGN?: T;
        stock?: T;
        image?: T;
        available?: T;
        id?: T;
      };
  inStock?: T;
  badge?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-gallery_select".
 */
export interface MediaGallerySelect<T extends boolean = true> {
  type?: T;
  title?: T;
  file?: T;
  thumbnail?: T;
  videoUrl?: T;
  quote?: T;
  publication?: T;
  author?: T;
  fileSize?: T;
  fileType?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscriptions_select".
 */
export interface SubscriptionsSelect<T extends boolean = true> {
  email?: T;
  firstName?: T;
  lastName?: T;
  type?: T;
  subscribedAt?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  organization?: T;
  inquiryType?: T;
  eventDate?: T;
  budget?: T;
  message?: T;
  submittedAt?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  customerEmail?: T;
  customerName?: T;
  shippingAddress?:
    | T
    | {
        line1?: T;
        line2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
        phone?: T;
      };
  items?:
    | T
    | {
        type?: T;
        productId?: T;
        variantId?: T;
        name?: T;
        variantLabel?: T;
        sku?: T;
        priceUSD?: T;
        priceNGN?: T;
        quantity?: T;
        id?: T;
      };
  subtotal?: T;
  shipping?: T;
  total?: T;
  displayCurrency?: T;
  status?: T;
  paymentProvider?: T;
  paidCurrency?: T;
  paidAmount?: T;
  credoReference?: T;
  credoAuthorizationUrl?: T;
  paypalOrderId?: T;
  paypalCaptureId?: T;
  lookupToken?: T;
  customerToken?: T;
  downloadToken?: T;
  downloadExpiresAt?: T;
  downloadCount?: T;
  emailsSent?:
    | T
    | {
        templateKey?: T;
        sentAt?: T;
        id?: T;
      };
  notes?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts_select".
 */
export interface CartsSelect<T extends boolean = true> {
  cartId?: T;
  customerEmail?: T;
  customerToken?: T;
  displayCurrency?: T;
  items?:
    | T
    | {
        type?: T;
        productId?: T;
        variantId?: T;
        name?: T;
        variantLabel?: T;
        sku?: T;
        priceUSD?: T;
        priceNGN?: T;
        quantity?: T;
        imageUrl?: T;
        id?: T;
      };
  itemCount?: T;
  lastActivityAt?: T;
  abandonedEmailSentAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-templates_select".
 */
export interface EmailTemplatesSelect<T extends boolean = true> {
  key?: T;
  enabled?: T;
  subject?: T;
  body?: T;
  fromName?: T;
  fromEmail?: T;
  replyTo?: T;
  variableDocs?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-logs_select".
 */
export interface EmailLogsSelect<T extends boolean = true> {
  templateKey?: T;
  to?: T;
  subject?: T;
  status?: T;
  resendId?: T;
  order?: T;
  error?: T;
  sentAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  category?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteTitle?: string | null;
  siteDescription?: string | null;
  ogImage?: (number | null) | Media;
  announcementBar?: {
    enabled?: boolean | null;
    text?: string | null;
    linkText?: string | null;
    linkUrl?: string | null;
    startDate?: string | null;
    endDate?: string | null;
  };
  epReleaseDate?: string | null;
  cdnUrl?: string | null;
  footerText?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  /**
   * Site-wide navigation links. Use the Locations field on each item to control whether it appears in the header, footer, or both.
   */
  navItems?:
    | {
        label?: string | null;
        url?: string | null;
        /**
         * Where this link appears. Leave empty to hide everywhere without deleting the row.
         */
        locations?: ('header' | 'footer')[] | null;
        /**
         * Only used when Footer is selected above. Items sharing the same column heading group together — e.g. type "Music" on three items and they appear in one column titled Music. Leave blank to fall under a default "Links" column.
         */
        footerColumn?: string | null;
        external?: boolean | null;
        cta?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteTitle?: T;
  siteDescription?: T;
  ogImage?: T;
  announcementBar?:
    | T
    | {
        enabled?: T;
        text?: T;
        linkText?: T;
        linkUrl?: T;
        startDate?: T;
        endDate?: T;
      };
  epReleaseDate?: T;
  cdnUrl?: T;
  footerText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        label?: T;
        url?: T;
        locations?: T;
        footerColumn?: T;
        external?: T;
        cta?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}